query = '''
SELECT BOOKS.ID,
       BOOKS.TITLE,
       COMMENTS.TEXT,
       DATA.NAME,
       DATA.FORMAT,
       DATA.UNCOMPRESSED_SIZE,
       IDENTIFIERS.TYPE,
       IDENTIFIERS.VAL,
       TAGS.NAME

FROM BOOKS

LEFT JOIN IDENTIFIERS ON BOOKS.ID = IDENTIFIERS.BOOK
LEFT JOIN DATA ON BOOKS.ID = DATA.BOOK
LEFT JOIN COMMENTS ON BOOKS.ID = COMMENTS.BOOK

LEFT JOIN (TAGS JOIN BOOKS_TAGS_LINK ON TAGS.ID = BOOKS_TAGS_LINK.TAG) BOOKS_TAGS_LINK ON BOOKS.ID = BOOKS_TAGS_LINK.BOOK

LEFT JOIN (PUBLISHERS JOIN BOOKS_PUBLISHERS_LINK ON PUBLISHERS.ID = BOOKS_PUBLISHERS_LINK.PUBLISHER) BOOKS_PUBLISHERS_LINK ON BOOKS.ID = BOOKS_PUBLISHERS_LINK.BOOK
;
'''
