sshd:
    build: ssh
    container_name: sshd
    entrypoint: /usr/local/bin/supervisord
    ports:
        - "722:722"
    expose:
        - "3773"
    dns: 127.0.0.1

mongodb:
    build: mongodb
    container_name: mongodb
    entrypoint: /usr/bin/mongod
    expose:
        - "27017"

library:
    build: library
    container_name: library
    entrypoint: /usr/local/bin/supervisord
    environment:
        LSB_DOMAIN: ${LSB_DOMAIN}
    expose:
        - "4321"
    links:
        - mongodb
        - sshd
    dns: 127.0.0.1

prosody:
    build: prosody
    container_name: prosody
    entrypoint: /usr/local/bin/supervisord
    environment:
        LSB_DOMAIN: ${LSB_DOMAIN}
    ports:
        - "5222:5222"
    expose:
        - "5280"
        - "5281"
    dns: 127.0.0.1

nginx:
    build: nginx
    container_name: nginx
    entrypoint: /usr/local/bin/supervisord
    ports:
        - "80:80"
        - "443:443"
    links:
        - sshd
        - library
        - prosody
    dns: 127.0.0.1
