rsync:
  build: rsync
  container_name: rsync
  entrypoint: /usr/local/bin/supervisord
  ports:
    - "8733:8733"
  volumes:
    - ${MOTW_HOME}/letssharebooks/memoryoftheworld/rsync/rsync.d/:/etc/rsync.d/
    - ${RSYNC_DIRECTORY}/rzynk/:/var/data/rzynk/

db:
  image: tutum/mysql:5.5
  container_name: db
  environment:
    MYSQL_PASS: "12345"
    MYSQL_USER: "wp_admin"
    #STARTUP_SQL: "/tmp/db/startup.sql"
  volumes:
    - /tmp/db/:/tmp/db/
    - ${MOTW_PERSISTENCE}/mysql/:/var/lib/mysql/
  expose:
    - "3306"

php5:
  build: php5
  container_name: php5
  entrypoint: /usr/local/bin/supervisord
  volumes: 
      - ${MOTW_WORDPRESS_HOME}/mu.memoryoftheworld.org/:/var/www/mu.memoryoftheworld.org
  expose:
      - "9000"
  links:
      - db

sshd:
    build: ssh
    container_name: sshd
    entrypoint: /usr/local/bin/supervisord
    ports:
        - "722:722"
    expose:
        - "3773"
    dns: 127.0.0.1

mongodb:
    build: mongodb
    container_name: mongodb
    entrypoint: /usr/bin/mongod
    #--------------------------------------------------------------------------
    #- in production this will make mongodb permanent at host -----------------
    volumes:
       - ${MOTW_PERSISTENCE}/mongodb/:/data/db/
    expose:
        - "27017"

library:
    build: library
    container_name: library
    entrypoint: /usr/local/bin/supervisord
    #--------------------------------------------------------------------------
    #- it might be good to uncomment this volume for webapp development -------
    # volumes: 
    #     - ${MOTW_HOME}/letssharebooks/library:/var/www/library
    environment:
        LSB_DOMAIN: ${LSB_DOMAIN}
    expose:
        - "4321"
    links:
        - mongodb
        - sshd
    dns: 127.0.0.1

prosody:
    build: prosody
    container_name: prosody
    entrypoint: /usr/local/bin/supervisord
    environment:
        LSB_DOMAIN: ${LSB_DOMAIN}
    ports:
        - "5222:5222"
    expose:
        - "5280"
        - "5281"
    dns: 127.0.0.1

nginx:
    build: nginx
    container_name: nginx
    entrypoint: /usr/local/bin/supervisord
    volumes:
      - ${MOTW_HOME}/letssharebooks/cache:/var/www/cache
      - ${RSYNC_DIRECTORY}/rzynk/:/var/www/rzynk/
      - ${MOTW_HOME}/letssharebooks/memoryoftheworld/nginx/sites-enabled/:/etc/nginx/docker_volumes/
    volumes_from:
        - php5
    ports:
        - "80:80"
        - "443:443"
    links:
        - sshd
        - library
        - prosody
        - php5
        - db
    dns: 127.0.0.1
