dnsdev:
  build: dnsdev
  container_name: dnsdev
  entrypoint: /sbin/my_int
  ports:
    - "53:53"
  links:
      - sshd
      - library
      - prosody
      - couchdb
      - nginx

couchdb:
  build: couchdb
  container_name: couchdb
  entrypoint: /usr/local/bin/supervisord
  expose:
    - "5984"

sshd:
    build: ssh
    container_name: sshd
    entrypoint: /usr/local/bin/supervisord
    ports:
        - "722:722"
    expose:
        - "3773"

mongodb:
    build: mongodb
    container_name: mongodb
    entrypoint: /usr/bin/mongod
    #--------------------------------------------------------------------------
    #- in production this will make mongodb permanent at host -----------------
    volumes:
       - /home/mnt/docker-persistence/mongodb/:/data/db/
    expose:
        - "27017"

library:
    build: library
    container_name: library
    entrypoint: /usr/local/bin/supervisord
    #--------------------------------------------------------------------------
    #- it might be good to uncomment this volume for webapp development -------
    # volumes: 
    #     - /home/m/devel/letssharebooks/library:/var/www/library
    environment:
        LSB_DOMAIN: motw.dev
    expose:
        - "4321"
    links:
        - mongodb
        - sshd

prosody:
    build: prosody
    container_name: prosody
    entrypoint: /usr/local/bin/supervisord
    environment:
        LSB_DOMAIN: motw.dev
    ports:
        - "5222:5222"
        - "5269:5269"
    expose:
        - "5280"
        - "5281"
    links:
        - library
    dns: ["127.0.0.1"]

nginx:
    build: nginx
    container_name: nginx
    entrypoint: /usr/local/bin/supervisord
    volumes:
      # - ./cache:/var/www/cache
      # - ./rsync/rzynk/:/var/www/rzynk/
      - ./nginx/sites-enabled/:/etc/nginx/docker_volumes/
    ports:
      - "80:80"
      # - "53:53"
      - "443:443"
    links:
      - sshd
      - library
      - prosody
      - couchdb
