#!/bin/sh

if [ -z $1 ]
   then
   echo "### USAGE:"
   echo "        \$ sudo ./msenter DOCKER-NAME"
   echo "### and it will expand to:"
   echo "        \$ nsenter --target \`sudo docker inspect --format {{.State.Pid}} memoryoftheworld_DOCKER-NAME_1\` --mount --uts --ipc --net --pid /bin/bash"
   echo "### second argument will replace '1' (after DOCKER-NAME)"
   echo "### third argument will replace 'memoryoftheworld' (after DOCKER-NAME 1)"
   exit
fi


NUM="1"
FIGPROJ="memoryoftheworld"

if [ $2 ] 
then       
   NUM=$2
fi

if [ $3 ]
then       
   FIGPROJ=$3
fi

nsenter --target `sudo docker inspect --format {{.State.Pid}} ${FIGPROJ}_$1_${NUM}` --mount --uts --ipc --net --pid /bin/bash